import {registerHooks} from 'node:module';
import {readFileSync,existsSync} from 'node:fs';
import {pathToFileURL,fileURLToPath} from 'node:url';
import path from 'node:path';
import ts from 'typescript';
import React from 'react';
import {renderToString} from 'react-dom/server';
const root=path.resolve('.');
registerHooks({resolve(spec,context,next){let file;if(spec.startsWith('@/'))file=path.join(root,spec.slice(2));else if(spec.startsWith('.')&&context.parentURL?.startsWith('file:')&&!context.parentURL.includes('/node_modules/'))file=path.resolve(path.dirname(fileURLToPath(context.parentURL)),spec);if(file){for(const ext of ['', '.ts','.tsx','.mts','.js'])if(existsSync(file+ext)&&!file.endsWith('/'))return next(pathToFileURL(file+ext).href,context);}return next(spec,context);},load(url,context,next){if(url.startsWith('file:')&&!url.includes('/node_modules/')&&/\.(tsx?|mts)$/.test(url)){let source=readFileSync(fileURLToPath(url),'utf8');if(url.endsWith('/app/page.tsx'))source+='\nexport { WeekView, TimeView, BalanceView, StabilityView, SubjectsView, MaterialsView, LongView, ExamsView, AIView, SettingsForm };';return {format:'module',shortCircuit:true,source:ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022,jsx:ts.JsxEmit.ReactJSX}}).outputText};}return next(url,context);}});
const A=await import('../lib/analysis.ts'),C=await import('../app/page.tsx');
const d=A.emptyData();d.subjects=[{id:'math',name:'数学',ideal_ratio:.5,target_days_per_week:5,color:'#b1f268'},{id:'en',name:'英語',ideal_ratio:.5,target_days_per_week:5,color:'#64c9ff'}];d.materials=[{id:'book',name:'教材',subject_id:'math',weekly_target_minutes:300}];d.goals.site.weekly_total_minutes=1400;for(const date of A.dates('2026-08-01','2026-10-08'))for(const s of d.subjects)d.study_records.push({date,subject_id:s.id,material_id:'book',duration_minutes:100,start_time:'18:00'});d.exam_results=[{date:'2026-09-01',name:'テスト模試',subject_id:'math',score:70,deviation:58}];const date='2026-10-08',w=A.week(d,date);let count=0;
for(const data of [A.emptyData(),d])for(const name of ['default','WeekView','TimeView','BalanceView','StabilityView','SubjectsView','MaterialsView','LongView','ExamsView','AIView','SettingsForm']){const props={d:data,date,w:A.week(data,date),history:A.weekHistory(data,8,date),f:n=>n==null?'—':String(n),period:'7',setPeriod:()=>{},go:()=>{},setPoint:()=>{},save:async()=>true,saving:false,draft:data,setDraft:()=>{},onSave:()=>{}};try{const html=renderToString(React.createElement(C[name],props));if(!html.length)throw Error('empty output');count++;}catch(e){console.error('FAIL',name,data.study_records.length,e);process.exit(1);}}
console.log('PASS: '+count+' empty/populated screen render cases');

const {ManualRecordForm}=await import('../components/manual-record-form.tsx');
for(const [data,materialId] of [[A.emptyData(),''],[d,''],[d,'book']]){const html=renderToString(React.createElement(ManualRecordForm,{data,date,materialId,saving:false,onSave:async()=>true,onClose:()=>{},onSettings:()=>{}}));if(!html.includes('保存して続ける')||!html.includes('学習時間の分'))throw Error('missing manual-entry controls');if(materialId&& !html.includes('教材に設定された科目を選択しました'))throw Error('missing automatic subject selection');}
console.log('PASS: manual entry renders for empty configuration, home entry, material entry');
const sortedFixture=A.emptyData();sortedFixture.subjects=[{id:'math',name:'数学',ideal_ratio:1}];sortedFixture.materials=[{id:'low',name:'少時間の教材',subject_id:'math'},{id:'high',name:'長時間の教材',subject_id:'math'},{id:'none',name:'未使用の教材',subject_id:'math'}];sortedFixture.study_records=[{date,material_id:'low',subject_id:'math',duration_minutes:10},{date,material_id:'high',subject_id:'math',duration_minutes:90},{date:'2027-01-01',material_id:'low',subject_id:'math',duration_minutes:1000},{date,material_id:'none',subject_id:'math',duration_minutes:0}];
const materialHtml=renderToString(React.createElement(C.MaterialsView,{d:sortedFixture,date,w:A.week(sortedFixture,date),f:String}));
if(!materialHtml.includes('selector-toolbar')||!materialHtml.includes('教材の並び順'))throw Error('missing aligned selectors/sort control');
if(!materialHtml.includes('<h2>長時間の教材</h2>'))throw Error('most-studied material not initially selected');
const usage=materialHtml.slice(materialHtml.indexOf('教材の使用状況'));if(!(usage.indexOf('長時間の教材')<usage.indexOf('少時間の教材')&&usage.indexOf('少時間の教材')<usage.indexOf('未使用の教材')))throw Error('usage table not sorted by valid elapsed study time');
const subjectHtml=renderToString(React.createElement(C.SubjectsView,{d:sortedFixture,date,w:A.week(sortedFixture,date),f:String}));const breakdown=subjectHtml.slice(subjectHtml.indexOf('教材内訳'));if(!(breakdown.indexOf('長時間の教材')<breakdown.indexOf('少時間の教材')))throw Error('subject breakdown not sorted');
console.log('PASS: page selectors and sort controls, most-studied initial selection, sorted materials and subject breakdown, future/invalid entries excluded');
