import {DatabaseSync} from 'node:sqlite';
import {readFileSync} from 'node:fs';
import assert from 'node:assert/strict';
import ts from 'typescript';
const sql=new DatabaseSync(':memory:');sql.exec(readFileSync('drizzle/0000_breezy_cannonball.sql','utf8'));
const wrap=(q)=>{let args=[];return {bind(...a){args=a;return this;},run(){const r=sql.prepare(q).run(...args);return {meta:{changes:r.changes}};},all(){return {results:sql.prepare(q).all(...args)};}}};
globalThis.__studyDb={prepare:wrap,async batch(ops){sql.exec('BEGIN');try{const r=ops.map(x=>x.run());sql.exec('COMMIT');return r;}catch(e){sql.exec('ROLLBACK');throw e;}}};
const analysis=await import('../lib/analysis.ts');
globalThis.__emptyData=analysis.emptyData;
const helper=ts.transpileModule(readFileSync('lib/data-management.ts','utf8').replace("import {emptyData, type Data} from './analysis';",'const emptyData=globalThis.__emptyData;'),{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}}).outputText;
globalThis.__clearLearningData=(await import('data:text/javascript;base64,'+Buffer.from(helper).toString('base64'))).clearLearningData;
let source=readFileSync('app/api/state/route.ts','utf8').replace("import {database} from '@/lib/storage';","const database=()=>globalThis.__studyDb;");
source=source.replace("import {clearLearningData} from '@/lib/data-management';",'const clearLearningData=globalThis.__clearLearningData;');
source=ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}}).outputText;
const {GET,PUT,DELETE}=await import('data:text/javascript;base64,'+Buffer.from(source).toString('base64'));
assert.deepEqual(await (await GET()).json(),{revision:0,data:null});
const base={study_records:[],subjects:[],raw:'あ'.repeat(220000)};
const req=(revision,data=base,origin='https://site.example')=>new Request('https://site.example/api/state',{method:'PUT',headers:{'Content-Type':'application/json',Origin:origin},body:JSON.stringify({data,revision})});
let result=await PUT(req(0));assert.equal(result.status,200);assert.deepEqual(await (await GET()).json(),{revision:1,data:base});
result=await PUT(req(0,{...base,raw:'stale'}));assert.equal(result.status,409);assert.deepEqual(await (await GET()).json(),{revision:1,data:base});
assert.equal((await PUT(req(1,base,'https://other.example'))).status,403);
assert.equal((await PUT(req(1,{study_records:'wrong'}))).status,400);
const next={...base,study_records:[{date:'2026-10-08',duration_minutes:30}]};assert.equal((await PUT(req(1,next))).status,200);assert.deepEqual(await (await GET()).json(),{revision:2,data:next});
assert.equal((await PUT(req(2,{...base,raw:'b'.repeat(8000001)}))).status,413);assert.equal((await (await GET()).json()).revision,2);
console.log('PASS: chunked UTF-8 roundtrip, atomic update, stale revision protection, origin validation, input validation, size limit without data loss');

const filled={...analysis.emptyData(),study_records:[{date:'2026-10-08',duration_minutes:30}],subjects:[{id:'en',name:'英語'}],materials:[{id:'book',subject_id:'en'}],exam_results:[{score:80}],imports:[{original:{study_records:[{secret:'original record'}]}}],score_history:[{minutes:30}],ai_reports:[{packet:{records:['secret']}}],records:['raw record'],duplicate_candidates:['duplicate'],metadata:{raw:'record metadata'},unknown_records:['extension record'],goal_history:[{before:{goals:{weekly_total_minutes:300}}}]};
assert.equal((await PUT(req(2,filled))).status,200);
const deletion=(revision,confirmation='削除',origin='https://site.example')=>new Request('https://site.example/api/state',{method:'DELETE',headers:{'Content-Type':'application/json',Origin:origin},body:JSON.stringify({revision,confirmation})});
assert.equal((await DELETE(deletion(3,'yes'))).status,400);
assert.equal((await DELETE(deletion(3,'削除','https://other.example'))).status,403);
assert.equal((await DELETE(deletion(2))).status,409);
assert.deepEqual((await (await GET()).json()).data,filled);
const batch=globalThis.__studyDb.batch;
globalThis.__studyDb.batch=async(ops)=>{sql.exec('BEGIN');try{ops[0].run();throw Error('simulated transaction failure');}finally{sql.exec('ROLLBACK');}};
const oldError=console.error;console.error=()=>{};
assert.equal((await DELETE(deletion(3))).status,503);
console.error=oldError;globalThis.__studyDb.batch=batch;
assert.deepEqual((await (await GET()).json()).data,filled);
result=await DELETE(deletion(3));assert.equal(result.status,200);
const cleared=await result.json();assert.equal(cleared.revision,4);
for(const key of ['subjects','materials','profile','goals','settings','exam_results','goal_history'])assert.deepEqual(cleared.data[key],filled[key]);
for(const key of ['study_records','imports','score_history','ai_reports'])assert.deepEqual(cleared.data[key],[]);
for(const key of ['records','duplicate_candidates','metadata','unknown_records'])assert.equal(Object.hasOwn(cleared.data,key),false);
assert.deepEqual(await (await GET()).json(),cleared);
assert.deepEqual(sql.prepare('SELECT DISTINCT revision FROM dashboard_chunks').all().map(x=>x.revision),[4]);
// A stale client cannot restore its previously loaded records after deletion.
assert.equal((await PUT(req(3,filled))).status,409);
assert.equal((await DELETE(deletion(3))).status,409);
// A write racing between the read and deletion batch also prevents deletion.
globalThis.__studyDb.batch=async(ops)=>{globalThis.__studyDb.batch=batch;await PUT(req(4,filled));return batch.call(globalThis.__studyDb,ops);};
assert.equal((await DELETE(deletion(4))).status,409);
assert.deepEqual((await (await GET()).json()).data,filled);
assert.equal((await DELETE(deletion(5))).status,200);
assert.deepEqual(sql.prepare('SELECT DISTINCT revision FROM dashboard_chunks').all().map(x=>x.revision),[6]);
sql.exec('DELETE FROM dashboard_chunks; DELETE FROM dashboard_state;');
assert.equal((await DELETE(deletion(0))).status,200);
assert.equal((await (await GET()).json()).data.profile.timezone,'Asia/Tokyo');
console.log('PASS: confirmed deletion, configuration preservation, imported copy purge, old revision purge, rollback, concurrent write protection, stale save protection, empty-state deletion');
