export type Data = Record<string, any> & {subjects:any[];materials:any[];study_records:any[];exam_results:any[];imports:any[];goals:any;profile:any};
export const defaults={balanceWeight:.4,stabilityWeight:.6,timeWeight:.7,zeroWeight:.2,continuityWeight:.1,tolerance:3,missingPenalty:5,gapPenalty:5,dominancePenalty:10,dominanceThreshold:80,excellent:90,good:75,fair:60};
export function emptyData():Data{return {schema_version:'1.0',profile:{week_start:'monday',timezone:'Asia/Tokyo',default_period:7,unit:'hm'},subjects:[],materials:[],study_records:[],exam_results:[],imports:[],goals:{studyplus:{weekly_total_minutes:null,raw:{}},site:{weekly_total_minutes:null,learning_condition_target:90}},settings:{...defaults},score_history:[],goal_history:[],ai_reports:[]};}
export const sum=(a:number[])=>a.reduce((x,y)=>x+y,0);
export const mean=(a:number[])=>a.length?sum(a)/a.length:0;
export const clamp=(x:number)=>Math.max(0,Math.min(100,x));
export const round=(x:number,n=1)=>Number(x.toFixed(n));
export const sd=(a:number[])=>Math.sqrt(mean(a.map(x=>(x-mean(a))**2)));
export function validDate(s:any){return typeof s==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(s)&&!isNaN(Date.parse(s))&&new Date(s).toISOString().slice(0,10)===s;}
export const addDays=(d:string,n:number)=>new Date(Date.parse(d+'T12:00:00Z')+n*86400000).toISOString().slice(0,10);
export const distance=(a:string,b:string)=>Math.round((Date.parse(b)-Date.parse(a))/86400000);
export const weekday=(d:string)=>new Date(d+'T12:00:00Z').getUTCDay();
export function today(tz='Asia/Tokyo'){return new Intl.DateTimeFormat('en-CA',{timeZone:tz,year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());}
export const weekStart=(d:string,start='monday')=>addDays(d,-((weekday(d)-(start==='sunday'?0:1)+7)%7));
export const dates=(a:string,b:string)=>Array.from({length:Math.max(0,Math.min(40000,distance(a,b)+1))},(_,i)=>addDays(a,i));
export const validRecord=(r:any)=>r&&validDate(r.date)&&typeof r.duration_minutes==='number'&&Number.isFinite(r.duration_minutes)&&r.duration_minutes>0&&r.duration_minutes<=1440;
export const records=(d:Data,a:string,b:string)=>d.study_records.filter(r=>validRecord(r)&&r.date>=a&&r.date<=b);
export const total=(r:any[])=>sum(r.map(x=>x.duration_minutes));
export const byKey=(rs:any[],key:string)=>rs.reduce((a:any,r:any)=>{const k=r[key]||'unknown';a[k]=(a[k]||0)+r.duration_minutes;return a;},{});
export function days(d:Data,a:string,b:string){const rs=records(d,a,b),tot=byKey(rs,'date');return dates(a,b).map(date=>({date,minutes:tot[date]||0,subjects:byKey(rs.filter(r=>r.date===date),'subject_id')}));}
export const firstDate=(d:Data)=>d.study_records.filter(validRecord).map(r=>r.date).sort()[0]||null;
export function confidence(d:Data,a:string,b:string){const f=firstDate(d),elapsed=distance(a,b)+1,history=f?distance(f,a):0;let c=elapsed>=5&&history>=28?2:elapsed>=3&&elapsed<=4||history>=14?1:0;const missing=d.study_records.filter(r=>!validRecord(r)||!d.subjects.some(s=>s.id===r.subject_id)).length;if(missing>Math.max(2,d.study_records.length*.1))c--;return ['LOW','MEDIUM','HIGH'][Math.max(0,c)];}
export function scores(d:Data,a:string,b:string){const cfg={...defaults,...d.settings},rs=records(d,a,b),ds=days(d,a,b),ts=ds.map(x=>x.minutes),t=total(rs),f=firstDate(d),ratioSum=sum(d.subjects.map(s=>Number(s.ideal_ratio)||0)),counts=byKey(rs,'subject_id');const valid=!!f&&f<=a&&ds.length>=3&&t>0&&d.subjects.length>0&&Math.abs(ratioSum-1)<.00001&&rs.every(r=>d.subjects.some(s=>s.id===r.subject_id));const subjects=d.subjects.map(s=>{const actual=t?(counts[s.id]||0)/t*100:0,ideal=(Number(s.ideal_ratio)||0)*100,diff=actual-ideal,adj=Math.max(0,Math.abs(diff)-(s.tolerance??cfg.tolerance));let penalty=0;if(ideal>=10&&actual===0)penalty+=cfg.missingPenalty;if(Math.abs(diff)>20)penalty+=cfg.gapPenalty;if(actual>cfg.dominanceThreshold)penalty+=cfg.dominancePenalty;const actualDays=new Set(rs.filter(r=>r.subject_id===s.id).map(r=>r.date)).size;const target=(Number(s.target_days_per_week)||0)*Math.max(1,ds.length/7);return {...s,minutes:counts[s.id]||0,actual,ideal,diff,adjusted:adj,penalty,loss:1.5*adj+penalty,actualDays,targetDays:target,continuity:target>0?Math.min(actualDays/target,1)*100:null};});const D=.5*sum(subjects.map(s=>s.adjusted)),penalty=sum(subjects.map(s=>s.penalty));const balance=clamp(100-3*D-penalty),avg=mean(ts),mad=mean(ts.map(x=>Math.abs(x-avg))),variation=mad/Math.max(avg,1),time=clamp(100-100*variation),zeroDays=ts.filter(x=>x===0).length,zero=ds.length?100*(1-zeroDays/ds.length):0;const continuityReady=subjects.every(s=>s.ideal===0||s.continuity!==null);const continuity=sum(subjects.map(s=>(s.continuity||0)*s.ideal/100));const stability=clamp(cfg.timeWeight*time+cfg.zeroWeight*zero+cfg.continuityWeight*continuity),condition=clamp(cfg.balanceWeight*balance+cfg.stabilityWeight*stability);const ready=valid&&continuityReady;return {balance:valid?balance:null,stability:ready?stability:null,condition:ready?condition:null,subjects,D,penalty,avg,mad,variation,time,zero,zeroDays,continuity,confidence:ready?confidence(d,a,b):'LOW',days:ds,minutes:t,sd:sd(ts),max:ts.length?Math.max(...ts):0,min:ts.length?Math.min(...ts):0,reason:!f?'学習記録を読み込んでください':f>a?'対象期間の先頭まで記録がありません':ds.length<3?'3日以上の記録期間が必要です':Math.abs(ratioSum-1)>.00001?'理想科目比率の合計を100%にしてください':!continuityReady?'科目の目標学習日数を設定してください':!t?'学習時間がありません':'未設定の科目を確認してください'};}
export const label=(v:number|null,cfg:any=defaults)=>v===null?'DATA INSUFFICIENT':v>=cfg.excellent?'EXCELLENT':v>=cfg.good?'GOOD':v>=cfg.fair?'FAIR':'NEEDS ATTENTION';
export const stabilityLabel=(v:number)=>v<=.15?'非常に安定':v<=.3?'安定':v<=.6?'やや不安定':'不安定';
export function goal(d:Data){const n=d.goals?.site?.weekly_total_minutes??d.goals?.studyplus?.weekly_total_minutes;return typeof n==='number'&&Number.isFinite(n)&&n>0&&n<=10080?n:null;}
export function week(d:Data,date=today(d.profile.timezone),asOf=today(d.profile.timezone)){const start=weekStart(date,d.profile.week_start),end=addDays(start,6),elapsed=distance(start,date)+1,remaining=8-elapsed,current=total(records(d,start,date)),g=goal(d),lastStart=addDays(start,-7),last=total(records(d,lastStart,addDays(start,-1))),rest=g===null?null:Math.max(0,g-current),projected=current/elapsed*7;return {start,end,date,elapsed,remaining,current,goal:g,rest,projected,required:rest===null?null:remaining?rest/remaining:rest===0?0:null,status:g===null?'目標未設定':end<asOf?current>=g?'ACHIEVED':'NOT ACHIEVED':projected>=g?'ON TRACK':projected>=g*.85?'AT RISK':'OFF TRACK',last,avg:current/elapsed,lastAvg:last/7,lastStart};}
export function weekHistory(d:Data,n=8,date=today(d.profile.timezone)){const w=week(d,date);return Array.from({length:n},(_,i)=>{const start=addDays(w.start,(i-n+1)*7),end=i===n-1?date:addDays(start,6);return {start,end,...scores(d,start,end)};});}
export function groupPeriod(d:Data,a:string,b:string,unit='week'){const ds=days(d,a,b),out:any={};for(const r of ds){const k=unit==='month'?r.date.slice(0,7):unit==='day'?r.date:weekStart(r.date,d.profile.week_start);out[k]=(out[k]||0)+r.minutes;}return Object.keys(out).sort().map(date=>({date,minutes:out[date]}));}
export function timeBands(rs:any[],tz='Asia/Tokyo'){const v:any={朝:0,昼:0,夕方:0,夜:0,不明:0};for(const r of rs){let hour:number|null=null;if(r.start_time){if(/^\d{1,2}:\d{2}/.test(r.start_time))hour=Number(r.start_time.split(':')[0]);else if(!isNaN(Date.parse(r.start_time)))hour=Number(new Intl.DateTimeFormat('en',{timeZone:tz,hour:'numeric',hourCycle:'h23'}).format(new Date(r.start_time)));}const k=hour===null?'不明':hour>=5&&hour<12?'朝':hour<17&&hour>=12?'昼':hour>=17&&hour<20?'夕方':'夜';v[k]+=r.duration_minutes;}return v;}
export function weekdayStats(d:Data,a:string,b:string){const ds=days(d,a,b);return Array.from({length:7},(_,offset)=>{const i=(offset+(d.profile.week_start==='sunday'?0:1))%7;const xs=ds.filter(x=>weekday(x.date)===i).map(x=>x.minutes);return {day:'日月火水木金土'[i],average:mean(xs),sd:sd(xs),zero:xs.filter(x=>!x).length,n:xs.length};});}
export function anomalies(d:Data,a:string,b:string){const f=firstDate(d),base=days(d,f&&f>addDays(a,-56)?f:addDays(a,-56),addDays(a,-1)).map(x=>x.minutes);if(base.length<7)return [];const m=mean(base),s=sd(base);return days(d,a,b).filter(x=>Math.abs(x.minutes-m)>Math.max(120,s*2)).map(x=>({...x,baseline:m,delta:x.minutes-m}));}
export function optimal(d:Data,a:string,b:string,remaining:number){const s=scores(d,a,b),alloc=s.subjects.map(x=>({id:x.id,name:x.name,minutes:0,current:x.minutes,ideal:x.ideal}));for(let i=0;i<Math.ceil(remaining);i++){let best=-1,gain=-Infinity;for(let j=0;j<alloc.length;j++){const x=alloc[j],target=(s.minutes+remaining)*x.ideal/100,def=target-x.current-x.minutes;if(def>gain){gain=def;best=j;}}if(best>=0)alloc[best].minutes+=Math.min(1,remaining-i);}const sim={...d,study_records:[...d.study_records,...alloc.map(x=>({date:b,duration_minutes:x.minutes,subject_id:x.id}))]};return {allocation:alloc,after:scores(sim,a,b).balance};}
export function simulate(d:Data,date:string,subject:string,minutes:number){const copy={...d,study_records:[...d.study_records,{date,subject_id:subject,duration_minutes:minutes}]};const start=weekStart(date,d.profile.week_start);return scores(copy,start,date);}
export function canonical(x:any):string{if(x===null||typeof x!=='object')return JSON.stringify(x)??'null';if(Array.isArray(x))return '['+x.map(canonical).join(',')+']';return '{'+Object.keys(x).sort().map(k=>JSON.stringify(k)+':'+canonical(x[k])).join(',')+'}';}
export function recordKey(r:any){if(r.source_id!==null&&r.source_id!==undefined&&r.source_id!=='')return 'source:'+String(r.source||'studyplus')+':'+String(r.source_id);return 'fields:'+canonical([r.date??null,r.start_time??null,r.end_time??null,r.material_id??null,r.subject_id??null,r.duration_minutes??null,r.content??null,r.comment??null]);}
export function mergeImport(base:Data,incoming:any){if(!incoming||typeof incoming!=='object'||Array.isArray(incoming)||!Array.isArray(incoming.study_records))throw new Error('study_records配列を含むJSONが必要です。元データは変更していません。');for(const key of ['subjects','materials','exam_results','imports'])if(incoming[key]!==undefined&&!Array.isArray(incoming[key]))throw new Error(key+' は配列で指定してください');if(incoming.study_records.some((r:any)=>!r||typeof r!=='object'||Array.isArray(r)))throw new Error('学習記録の構造を確認してください');if(incoming.profile&&(typeof incoming.profile!=='object'||Array.isArray(incoming.profile)))throw new Error('profileの形式が不正です');for(const key of ['score_history','goal_history','ai_reports'])if(incoming[key]!==undefined&&!Array.isArray(incoming[key]))throw new Error(key+'は配列が必要です');
if(incoming.settings){const c={...defaults,...incoming.settings};if(Object.values(c).some(v=>typeof v!=='number'||!Number.isFinite(v)||v<0)||Math.abs(c.balanceWeight+c.stabilityWeight-1)>.00001||Math.abs(c.timeWeight+c.zeroWeight+c.continuityWeight-1)>.00001)throw new Error('計算設定の数値または重みの合計が不正です');}
const d:Data=structuredClone(base),warnings:string[]=[];let duplicates=0;const keys=new Map(d.study_records.map(r=>[recordKey(r),r]));const ids=new Map(d.study_records.filter(r=>r.id).map(r=>[r.id,r]));if(incoming.schema_version&&incoming.schema_version!=='1.0')warnings.push('未対応のschema_version。既知の項目のみ集計し、全項目を保持します。');const known=new Set(['id','source','source_id','date','start_time','end_time','duration_minutes','subject_id','material_id','content','comment','raw']);for(const [i,r] of incoming.study_records.entries()){const key=recordKey(r),old=keys.get(key);if(old){duplicates++;if(canonical(old)!==canonical(r))warnings.push(`記録${i+1}: 同一記録の追加項目・変更候補を原本に保持しました。既存記録は上書きしません。`);continue;}if(r.id&&ids.has(r.id))warnings.push(`記録${i+1}: idが既存記録と一致しますが内容が異なります。両方保持します。`);if(d.study_records.some(x=>x.date===r.date&&x.material_id===r.material_id&&x.subject_id===r.subject_id&&x.duration_minutes===r.duration_minutes))warnings.push(`記録${i+1}: 重複候補。自動削除せず追加します。`);if(!validRecord(r))warnings.push(`記録${i+1}: 日付または時間が不正・0分・24時間超です。保持しますが集計から除外します。`);if(Object.keys(r).some(k=>!known.has(k)))warnings.push(`記録${i+1}: 追加項目を保持しました。仕様変更の可能性があります。`);d.study_records.push(r);keys.set(key,r);if(r.id)ids.set(r.id,r);}
for(const key of ['subjects','materials'] as const)for(const row of incoming[key]||[]){if(typeof row?.id!=='string'||!row.id||typeof row.name!=='string')throw new Error(key+'のid・nameが必要です');const old=d[key].find(x=>x.id===row.id);if(old){for(const k of Object.keys(row))if(old[k]===undefined)old[k]=row[k];}else d[key].push(row);}
for(const r of incoming.exam_results||[]){if(!r||typeof r!=='object')throw new Error('模試項目の形式が不正です');if(!d.exam_results.some(x=>canonical(x)===canonical(r)))d.exam_results.push(r);if(!r.date||!r.name||!r.subject_id||r.score==null||r.deviation==null)warnings.push('模試に欠損項目があります。取得済み項目のみ表示します。');}
if(incoming.goals?.studyplus)d.goals.studyplus={...d.goals.studyplus,...incoming.goals.studyplus};if(!base.study_records.length){if(incoming.profile)d.profile={...d.profile,...incoming.profile};if(incoming.goals?.site)d.goals.site={...d.goals.site,...incoming.goals.site};for(const k of ['settings','score_history','goal_history','ai_reports'])if(incoming[k]!==undefined)d[k]=incoming[k];}
for(const k of Object.keys(incoming))if(!(k in d))d[k]=incoming[k];for(const sub of d.subjects){for(const k of ['ideal_ratio','weekly_target_minutes','target_days_per_week'])if(sub[k]!=null&&(typeof sub[k]!=='number'||!Number.isFinite(sub[k])||sub[k]<0))throw new Error(sub.name+' の '+k+' は0以上の数値で指定してください');if(sub.ideal_ratio>1||sub.target_days_per_week>7)throw new Error(sub.name+' の理想比率または学習日数が範囲外です');}if(d.profile.week_start!=='monday'&&d.profile.week_start!=='sunday')throw new Error('週の開始曜日はmondayまたはsundayにしてください');
if(goal(d)===null)warnings.push('有効な週間目標がありません。0分・未設定・10080分超は目標未設定として扱います。');const added=d.study_records.length-base.study_records.length;const unknown=d.study_records.filter(r=>!d.subjects.some(s=>s.id===r.subject_id)).length;if(unknown)warnings.push(`科目未設定の記録が${unknown}件あります。スコア計算には科目設定が必要です。`);if(Math.abs(sum(d.subjects.map(s=>Number(s.ideal_ratio)||0))-1)>.00001)warnings.push('理想科目比率の合計が100%ではありません。');if(d.profile.timezone){try{today(d.profile.timezone)}catch{throw new Error('timezoneが不正です。JSONを確認してください');}}d.imports.push({imported_at:new Date().toISOString(),added_records:added,duplicate_records:duplicates,warnings,original:incoming});d.updated_at=new Date().toISOString();return {data:d,added,duplicates,warnings};}
export function snapshot(d:Data,reason:string){const date=today(d.profile.timezone),s=scores(d,weekStart(date,d.profile.week_start),date);const snap={at:new Date().toISOString(),date,condition:s.condition,balance:s.balance,stability:s.stability,confidence:s.confidence,reason,settings:{...defaults,...d.settings}};return {...d,score_history:[...(d.score_history||[]),snap]};}
export function packet(d:Data,kind:string,date=today(d.profile.timezone)){const monthA=monthStartOffset(date,0),monthP=monthStartOffset(date,-1),monthLast=addDays(monthA,-1),monthlyCurrent=total(records(d,monthA,date)),monthlyPrevious=total(records(d,monthP,monthLast));const w=week(d,date),a=kind==='月間分析'?date.slice(0,7)+'-01':w.start,previousStart=kind==='月間分析'?new Date(Date.UTC(Number(date.slice(0,4)),Number(date.slice(5,7))-2,1)).toISOString().slice(0,10):addDays(w.start,-7),previousEnd=addDays(a,-1);return {schema_version:'1.0',analysis_type:kind,generated_at:new Date().toISOString(),range:{start:a,end:date},week:w,comparisons:{weekly_minutes_difference:w.current-w.last,weekly_daily_average_difference:w.avg-w.lastAvg,monthly_current_minutes:monthlyCurrent,monthly_previous_minutes:monthlyPrevious,monthly_minutes_difference:monthlyCurrent-monthlyPrevious,current_month_is_partial:true},metrics:scores(d,a,date),previous: scores(d,previousStart,previousEnd),weekly_trend:weekHistory(d,8,date),monthly_trend:groupPeriod(d,firstDate(d)||a,date,'month'),subjects:d.subjects,materials:d.materials.map(m=>({...m,minutes:total(records(d,a,date).filter(r=>r.material_id===m.id))})),anomalies:anomalies(d,a,date),goals:d.goals,exams:kind==='模試込み総合分析'?d.exam_results:undefined,data_quality:{warnings:d.imports.flatMap(i=>i.warnings||[]),assumption:'取得範囲内の記録がない日は0分として集計。取得範囲外は評価しない。'},instructions:'事実・解釈・改善案を分離し、日本語で分析してください。因果関係を断定せず、欠損を補完しない。返答JSON: {"facts":["..."],"interpretations":["..."],"suggestions":["..."]}'};}
export function movingAverage(d:Data,date:string){const f=firstDate(d);if(!f||date<f)return null;return mean(days(d,f>addDays(date,-2)?f:addDays(date,-2),date).map(x=>x.minutes));}
export function monthStartOffset(date:string,n:number){return new Date(Date.UTC(Number(date.slice(0,4)),Number(date.slice(5,7))-1+n,1)).toISOString().slice(0,10);}
export function getExamRows(d:Data){return d.exam_results.flatMap(e=>Array.isArray(e.subjects)?e.subjects.map((s:any)=>({...e,...s,subjects:undefined,raw_exam:e})):Array.isArray(e.results)?e.results.map((s:any)=>({...e,...s,results:undefined,raw_exam:e})):[e]);}
